### ISSUE TITLE
List of valid sdb shell commands

### ISSUE THREAD

**Issue by AndreasNasman** [Samsung/Wits#101]
This might be the wrong place to ask, but I haven't found any information anywhere on valid commands to give `sdb shell`.

The official documentation only mentions commands when you have SDB remote shell access:
https://developer.tizen.org/development/tizen-studio/web-tools/running-and-testing-your-app/sdb#issuing_commands

I work with Samsung Hotel TVs and SSSP screens where shell access is locked, so a basic `sdb shell ls` outputs nothing.

In this project and [webIDE-common-tizentv/](https://github.com/Samsung/webIDE-common-tizentv/) (which is used the hood in the [vscode-extension-tizentv](https://github.com/Samsung/vscode-extension-tizentv)), you both use a `sdb shell 0 <command>` syntax, e.g. with `<command>` as `debug`:
- https://github.com/Samsung/Wits/blob/a3d1c32b07d8a0bff176ddc08228c11e07cdc963/lib/appLaunchHelper.js#L70
- https://github.com/Samsung/webIDE-common-tizentv/blob/8e3b4acd9f20436527fe233d8aadc1ba98b39b4e/lib/appLauncher.js#L104

Questions:
1. What does the `0` mean?
1. How do you know that `debug` is a valid `<command>` to give `sdb shell 0 <command>`? Can I somehow see all valid commands?

I've asked the Samsung B2B Q&A the same question, but they had no answer.

Thanks,
– Andreas

**Comment by pwsses** [comment]
Hello. 
The 0 is some kind of keyword about TV device. it doesn't mean anything.
And There is no providing command list.

As you know, unfortunately, A common shell command is not allowed in TV devices.
Thanks.

**Comment by AndreasNasman** [comment]
Ok, thanks for the information!
