### ISSUE TITLE
Getting "closed" when calling sdb -s 10.8.82.242:26101 shell 0 debug UQFmc9jZyO.Wits

### ISSUE THREAD

**Issue by jfrux** [Samsung/Wits#11]
Getting a little further...
Works fine on the `was_execute`-style command...

Any tips on how to get my app to run debug mode?

**Comment by pwsses** [comment]
Hi
In 2016 device sdb command needs one more parameter. which is timeout value.
So you would can try like this "sdb -s deviceName 0 debug appID 0"
If doesn't enable 0 (timeout value), try other number.

Thank you.

**Comment by jfrux** [comment]
I'll do some testing and if I can get it all working, I'll write it in a universal way so that it supports both and submit a PR.
