### ISSUE TITLE
[Improvement] Host ip config

### ISSUE THREAD

**Issue by mdabrowski2** [Samsung/Wits#15]
Hello,
I'd like to introduce a small new feature into Wits which is manually setting host ip by adding field "hostIP" in profileInfo.json.
There's an issue when I'm trying to connect to Wits on my TV via LAN.
The problem is Wits automatically sets host ip with the "ip" library and it uses my external address while I need him to connect with me with 192.168.137.1 address.
I would like to add a simple feature allowing user to input his own host ip manually, overriding the ip library.

**Comment by pwsses** [comment]
Hello,
Thank you for your suggestion. I using "ip" library on PC side. And I couldn't think of the situation as your env. It is very special situation but if adding a new property, I think it is better to be located new json file like hostInfo.json. If you summit PR, I will check and merge it.
Thank you.
