### ISSUE TITLE
[Fix] Wits doesn't run with debug on 2017 device

### ISSUE THREAD

**Issue by mdabrowski2** [Samsung/Wits#16]
Hello,
Wits doesn't seem to be able to launch app with debug mode (web inspector) on my 2017 Smart TV. It seems to be connected with issue #11 in which @jfrux said 

> I'll do some testing and if I can get it all working, I'll write it in a universal way so that it supports both and submit a PR.

but it doesn't look like it went anywhere from there so if you don't mind I'd like to submit a PR in which I will add the 300 miliseconds delay at the end of the command like `sdb -s deviceName 0 debug appID 300`
300 miliseconds delay always worked for me and I tested dozens of SmartTVs.

**Comment by pwsses** [comment]
Hello,
Thank you for your opinion. I also test your recommend on 2019 TV. It work fine.
If you submit PR, I will check and merge it.
Thank you.

**Comment by mdabrowski2** [comment]
The solution was merged into master, so I'm closing the issue.
Thank you @pwsses
