### ISSUE TITLE
Install Wits

### ISSUE THREAD

**Issue by zgelici** [Samsung/Wits#19]
Hello,  can someone help me please. i cannot install Wits.

This is the message what i get:

Start packaging Samsung Tizen TV Platform......
Tizen CLI 2.5.5
Setting configuration is succeeded....

Build Web Application:  100% (10/10)

BUILD SUCCESSFUL

Output path : E:\projects\Wits\tizen\.buildResult
Excluded : [.build/*, .build, .sign/*, .sign, webUnitTest/*, webUnitTest, .externalToolBuilders/*, .externalToolBuilders, .buildResult/*, .buildResult, .settings/*, .settings, .package/*, .package, .tproject, .project, .sdk_delta.info, .rds_delta, *.wgt, .tizen-ui-builder-tool.xml]
Total time: 00:00:00.777
Warning: Not found tizen signature file
Warning: Not found tizen author signature file
Excludes File Pattern: {.manifest.tmp, .delta.lst}
Package File Location: E:\projects\Wits\tizen\.buildResult\Wits.wgt
Package created at E:\projects\Wits\tizen\build\Wits.wgt

[Warning] Failed to uninstall Wits
Start install package...

Start install package...

Failed to install Wits

Thanks

**Comment by pwsses** [comment]
Hi
it looks like profile issue. please check profileInfo.json file. 
In ReadMe, I write about that. please refer it.
--
Modify profileInfo.json
Fill out your profile name and path for Tizen Web application package.
--

**Comment by zgelici** [comment]
hi @pwsses 

Thanks for you response. the profilename was not correct. 

Its working now

Thanks
