### ISSUE TITLE
Failed to un/install Wits

### ISSUE THREAD

**Issue by ironprogrammer** [Samsung/Wits#20]
After the build succeeds, I receive the following errors:

```bash
Start packaging Samsung Tizen TV Platform......
Tizen CLI 2.5.5
Setting configuration is succeeded....

Build Web Application:  100% (10/10)

BUILD SUCCESSFUL

...[snip]...

[Warning] Failed to uninstall Wits
exec: error: too few arguments

Start install package...

Failed to install Wits
```

The device is a 2018 PM32F-BC. I tried installing the built Wits/tizen/build/Wits.wgt directly through Device Manager, too, but received a `closed` response.

Would you happen to have any clues as to what I'm doing wrong? Thanks!

**Comment by pwsses** [comment]
Hi
Thanks for your report. 
I searched your device spec. 
Unfortunately, It has tizen 2.4 operating system even if 2018 product.
WITS is supported in version 3.0 or later.

Thank you.
