### ISSUE TITLE
'sdb' is not recognized error on application launch

### ISSUE THREAD

**Issue by Guidogl** [Samsung/Wits#23]
Hello,

After Wits configuration, I am trying to launch it but I get the following error: `'sdb' is not recognized as an internal or external command,
operable program or batch file.
exec: 'sdb' is not recognized as an internal or external command,
operable program or batch file.`

Sometimes I get this error when launching debug mode in Tizen Studio. Still can't figure out what is the problem. I am using Windows and it is probably issue with PATH.

**Comment by BaiMaoLi** [comment]
Hello, I faced same issue, Did you solve that?

**Comment by mary-lydia-j** [comment]
Did anyone sort it ?
