### ISSUE TITLE
exec: 'sdb' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by BaiMaoLi** [Samsung/Wits#27]
I am using wits on windows and when I start "npm run", I am getting this error.
**exec: 'sdb' is not recognized as an internal or external command,
operable program or batch file.**

I installed it on D, and add environment variable "D:\wits",
still getting error.
Please help me. thanks.

**Comment by pwsses** [comment]
Hi
You should set sdb path (ex, C:\tizen-studio\tools) in window environment PATH
Please refer WITs readME file.
Thank you.

**Comment by BaiMaoLi** [comment]
Thanks, 
I just found that and solved.
Now I am getting new issue.
**"Failed to connect 0.0.0.0"**
Possible to help me with this?
Or should I create new issue?

**Comment by pwsses** [comment]
Maybe you input target IP with 0.0.0.0 which is for emulator.
If you use emulator, turn on the emulator.

**Comment by BaiMaoLi** [comment]
I am running with simulator.
Simulator is different from emulator?
I turned on Simulator.
But not working.

**Comment by pwsses** [comment]
Sorry, Wits doesn't support simulator. 
Simulator is very faster than TV and emulator. 
it doesn't need any package and install.
As I know, It similar to PC browser.

**Comment by BaiMaoLi** [comment]
OK. i see.
And sorry for taking your time.
But, from tizen studio 3.6, I can't run emulator manager.
It asked me to enable from firewall, I enabled, nothing happned.
I tried so much, but still can't run emulator manager.
Do you have any idea?
Thanks for your support.

**Comment by pwsses** [comment]
Additionally, 
Tizen web application based on single page web. So If you want control key event, bind keydown handler in body tag.

**Comment by pwsses** [comment]
Sorry I can'y help about emulator manager. 
How about make question in Samsung developer site?
thank you

**Comment by BaiMaoLi** [comment]
I see.
so, should I handle all key event manually?
I am doing this, but it is really hudge work.
Is there no any prebuilt plugin?

**Comment by pwsses** [comment]
It supported all web-based plugin. 
ex) https://github.com/react-tv/react-tv-navigation

**Comment by BaiMaoLi** [comment]
OK.
the sdb issue is solved in my side, so I am closing this issue.
