### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: REG_BACKSLASH is not defined

### ISSUE THREAD

**Issue by BaiMaoLi** [Samsung/Wits#28]
I am getting this error.
**UnhandledPromiseRejectionWarning: ReferenceError: REG_BACKSLASH is not defined**

**Comment by pwsses** [comment]
Than you for your help. 
I will fixed and push it.

**Comment by BaiMaoLi** [comment]
OK.
By the way, can we discuss more via skype or email?
I have some questions, and if you help me it would be great.
I've sent email to you.

**Comment by BaiMaoLi** [comment]
Hello, any update?

**Comment by pwsses** [comment]
Hello
I already Fixed this issue(Fixed Bug from userInfoHelper). and Push to repository.
Thank you

**Comment by BaiMaoLi** [comment]
Oh, great. thanks.
let me check.

**Comment by BaiMaoLi** [comment]
Sorry, still same
(node:21268) UnhandledPromiseRejectionWarning: ReferenceError: REG_BACKSLASH is not defined
    at Object.getUserAnswer (D:\Wits\lib\userInfoHelper.js:22:88)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async startWits (D:\Wits\app.js:18:22)
(node:21268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecti
ng a promise which was not handled with .catch(). (rejection id: 1)
(node:21268) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process wit
h a non-zero exit code.

**Comment by pwsses** [comment]
Please one more check.
I fixed that REG_BACKSLASH -> regExp.BACKSLASH on line 20 in userInfoHelper.js

**Comment by BaiMaoLi** [comment]
OK. I saw that.
I am trying now.

**Comment by BaiMaoLi** [comment]
Now Backslash error not occured.
But I am getting another error.

This is current setting
**{
  baseAppPath: 'E:/Work/Current Work/Samsung/SmartTvProject',
  width: '1920',
  ip: '0.0.0.0',
  port: '8498',
  isDebugMode: true
}**

This is error message
**Failed to connect 0.0.0.0**

I am using emulator.
