### ISSUE TITLE
Message error

### ISSUE THREAD

**Issue by SejoongDeJang** [Samsung/Wits#32]
wits --start 수행 후 실패시 메세지 깨집니다

connect to.... xxx.xxx.xxx.xxx
'sdb'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.
Failed to connect xxx.xxx.xxx.xxx

환경
window 10, tizen studio 설치 하지 않음
powershell, cmd 동일한 이슈 발생합니다.

**Comment by pwsses** [comment]
window 환경에서 powershell / cmd 등에서 한글 언어로 변경하면 표시됩니다.
chcp 65001 로 설정후 확인 바랍니다.
