### ISSUE TITLE
Please add support to generate Samsung partner certificate

### ISSUE THREAD

**Issue by mainendra** [Samsung/Wits#80]
Certificate manager is not working on mac os big sur (because it is using java 1.8 🤔 ).
It would be really helpful if we can generate samsung parter certificate  using CLI so no UI needed.
We can use any IDE for development.

**Comment by prozanne** [comment]
Hi!
Well if you download Atom editor and install atom-tizentv-2, you can actually create a samsung partner certification with it.
Could you please try it?
1. Download Atom editor
2. apm install atom-tizentv-2

And which Mac or Tizen Studio version are you using now?
If you have any problem with it, I will ask about the issue to Tizen Studio.
Or maybe you can directly make a topic to the forum.
https://forum.developer.samsung.com/c/smart-tv/22

**Comment by mainendra** [comment]
Thanks @prozanne , It worked. This is good enough. I'm kind of command line person so I was looking for some kind of command line utility similar to `wits -c`. We can close this issue if you want or convert it into enhancement instead of bug.

Tizen studio is really slow, Atom is much better. I'm using tizen studio 4.0, UI is really messed up on mac os 11 (big sur)
<img width="985" alt="tizen-sdk" src="https://user-images.githubusercontent.com/1897340/99757863-8e4c3580-2aad-11eb-88f7-5fef11ac7b45.png">
<img width="1001" alt="tizen-sdk-settings" src="https://user-images.githubusercontent.com/1897340/99757867-91472600-2aad-11eb-9699-c4653bf528cf.png">
All settings are throwing error.
If you want please follow up with Tizen studio team. Thanks.

**Comment by prozanne** [comment]
Hi!
I've just checked it with Tizen Studio,
and they said as it's known issue on Big Sur, they will fix it at the end of Nov or at the start of Dec.
The version of Tizen Studio will be fixed the issue! (It will be Tizen Studio 4.1)
After releasing please update the version.

And I agree with "supporting samsung certificate" too.
We will consider it positively.
Many thanks!

**Comment by prozanne** [comment]
Hi :)

I heard Tizen Studio will update within Dec.
It will be next week＋α.

Thanks.
This issue will be closed.
