### ISSUE TITLE
`.witsignore` file location: Better to use `process.cwd()` than `baseAppPath`

### ISSUE THREAD

**Issue by easingthemes** [Samsung/Wits#82]
`.witsignore` is not part of the app files, just Project helper. 
Location should not be in `baseAppPath`, but rather in `process.cwd()`.

This works fine for `.witsconfig.json`:
Current:
```
|-- Project/
    .witsconfig.json
    |-- app (baseAppPath)/
        .witsignore
```
Should be:
```
|-- Project/
    .witsconfig.json
    .witsignore
    |-- app (baseAppPath)/
```

Codebase: https://github.com/Samsung/Wits/blob/master/lib/watchHelper.js#L84

**Comment by pwsses** [comment]
Thank you for your opinion.
But I think ignore file should located for each app project. because WITs is installed globally, and Each app can have different ignore option.
Thank you.

**Comment by easingthemes** [comment]
1. WITs work fine locally as any other npm package.
Handling dependencies per project is better than any global config.
Even NodeJs can be local installation. This way Projects are totally decoupled from any environment.

2. `But I think ignore file should located for each app project` - yes I agree here, app project usually contains a lot of development code which is not meant for final production part of the app.
Eg eslint, stylelint, node_modules, .witsconfig.json, .git, - all  of this are just helper files, and app distribution files are in `baseAppPath`.
`baseAppPath` should contain only final app code, no development helpers. Currently every location is fine, except of `.witsignore`

**Comment by pwsses** [comment]
Thank you for detail review and opinion. I agree 
`baseAppPath should contain only final app code,` - I agree.  
I considered it like `.gitIgnore`. and Users can conveniently modify ignore option each app.
I will consider a good way to update next time.
You know what. When you package a tizen app(.wgt), you can treat a specific file as an exception.
