### ISSUE TITLE
Read `deviceIp` from cli options or `.env` files

### ISSUE THREAD

**Issue by easingthemes** [Samsung/Wits#84]
In order to avoid changing `.witsconfig.json` non stop when switching between emulator and real device, it would be good to make `deviceIp` configurable, either reading it from cli options or `.env` files.
Or even make `.witsconfig.json` available as `.js` file so that we can do this on our end.

**Comment by prozanne** [comment]
Hi :)

I will consider the feature that the value of the "deviceIp" can be inputted from cli option.
The usage will be "wits -s --deviceIp=0.0.0.0" like that.
I will let you know if we support it.

Thanks.

**Comment by easingthemes** [comment]
Great, thanks.

**Comment by prozanne** [comment]
Hi,

The PR has been merged.
I will let you know after releasing WITs (v2.4.8).

The usage is "wits -s deviceIp=0.0.0.0" or "wits -w deviceIp=0.0.0.0"
Thanks!
The issue will be closed.

**Comment by prozanne** [comment]
WITs has been released v2.4.8.

You can use the feature,
wits -s deviceIp=x.x.x.x
wits -w deviceIp=x.x.x.x

Thanks!
