### ISSUE TITLE
Failed to install WITs

### ISSUE THREAD

**Issue by DavidCrandall-charter** [Samsung/Wits#90]
So, I think I have everything set up right in my permissions per this and I can make a 'wgt' file independently with the 'tizen command.   So, certificates look right.

https://developer.samsung.com/smarttv/develop/getting-started/using-sdk/command-line-interface.html

However, I try to do 

`wits -s`

...and with a little bit of enhanced logging magic (setting `{silent: false}` where needed in the library), I get this.

```
Start running Wits............

[@tizentv/tools]tools.getToolPath: toolName = sdb

      > [ Stored Information ]

      > baseAppPath  : /Users/p2713850/samsung-tv/samsung-tizen-wrapper
      > width        : 1280
      > deviceIp     : 192.168.2.3
      > isDebugMode  : false

      > profile path : /Users/p2713850/profiles.xml
      > hostIp       : 192.168.2.1

connect to....192.168.2.3
Success to connect 192.168.2.3
content src is : index.html

Start packaging Samsung Tizen TV Platform......

[webide-common-tizentv]projectHelper.buildWidget() profilePath = /Users/p2713850/profiles.xml, excludeFiles = undefined
After build package, signature tempory files were removed
[webide-common-tizentv]projectHelper.widget.on(): Build Package completed!
============================== Build Package completed!

============================== Start to install the package

[warning] Failed to uninstall Wits, yo. /Users/p2713850/tizentv-tools/sdb/sdb -s 192.168.2.3:26101 shell 0 vd_appuninstall TizenWrapperWITs 
uninstall TizenWrapperWITs
app_id[TizenWrapperWITs] uninstall start
app_id[TizenWrapperWITs] uninstall failed[132]
spend time for wascmd is [8]ms
cmd_ret:0

Failed to install Wits /Users/p2713850/tizentv-tools/sdb/sdb -s 192.168.2.3:26101 shell 0 vd_appinstall TizenWrapperWITs /home/owner/share/tmp/sdk_tools/WITs.wgt 
install TizenWrapperWITs
package_path /home/owner/share/tmp/sdk_tools/WITs.wgt
was_install_app return WAS_TRUE
app_id[TizenWrapperWITs] install start
app_id[TizenWrapperWITs] installing[10]
app_id[TizenWrapperWITs] installing[12]
app_id[TizenWrapperWITs] installing[15]
app_id[TizenWrapperWITs] installing[17]
app_id[TizenWrapperWITs] installing[20]
app_id[TizenWrapperWITs] installing[22]
app_id[TizenWrapperWITs] installing[25]
app_id[TizenWrapperWITs] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [765]ms
cmd_ret:0
➜  samsung-tizen-wrapper git:(master) ✗ 
```

Now, my one concern is that I may not have this connected, however if I do:

`sdb devices`

I show connected to my TV.

So that can't be.  Certificate looks right.  Connection to the TV looks right (checked IP pairing).

**Comment by prozanne** [comment]
Hi,

Even though packaging is done and connection is good,
the certification can be a matter. (When certification is created, it needs a DUID information. So unknown can't install an application to your device.)
Could you please check you pushed your certification to your target device?

You can refer below guide of Tizen Studio. (Search "Permit to install applications")
https://developer.samsung.com/smarttv/develop/getting-started/using-sdk/command-line-interface.html

If still you are in a problem, please let me know.

Thanks.

**Comment by DavidCrandall-charter** [comment]
Thank you for the quick response!  I really appreciate it.

Ok, did the tizen studio 'permit to install applications' -

<img width="852" alt="Screen Shot 2020-12-30 at 9 30 30 AM" src="https://user-images.githubusercontent.com/65182976/103369813-552dba80-4a88-11eb-8eaa-8546659eb754.png">

However, I'm still getting some level of failure.   The version mismatch is new, so I'm not sure what I'm doing.  I'm running with a QN43Q60 and I did check for updates.

[whatever.txt](https://github.com/Samsung/Wits/files/5755061/whatever.txt) 
(basically the error keeps happening)

Also - is there a command-line way to certify/upload a certificate to the TV?   Basically I'm trying to automate and simplify pushing an application without using any sort of a graphical user interface, if I can avoid it.  

Also - one last question, there isn't a list of sdb shell commands, like `vd_appuninstall` , somewhere, is there?

**Comment by prozanne** [comment]
Hi!

Now it seems ready for installing an application, but I am still thinking there is an issue of a certification.
Could you please check when you create a basicProject on the Tizen studio, It could be installed on your target? (Check with Run as).
If it works, please set a profile path of WITs to the path worked well at the Tizen Studio. And try WITs again.
It's just for making sure that your environment works well originally.
Because basically WITs uses sdb for installing an application just like Tizen studio does.
And as I know.... the sdb version mismatches error is not a fatal error, It might be a just warning.

And about the 2nd question, I am not working for Tizen Studio, so I am not sure. But I think It's not supported. And I know It's so necessary feature for using only CLI without GUI. So WITs is considering to support the feature in the future. (TBD)

About the last one, I only found an official [SDB Guide](https://developer.tizen.org/development/tizen-studio/web-tools/running-and-testing-your-app/sdb) this guide.

Thanks.

**Comment by DavidCrandall-charter** [comment]
Ah, that got it.   Thank you!  Happy New Year!

So, I had to put the profile path to the one generated by the tizen studio certificate manager.  The certificates we use are 'Samsung' certificates and not 'Tizen' ones (it's like, Samsung->'TV'->generate-> login->fill-in DUID.   I think I can kind of get around a lot of our needs with Tizen studio, but it still seems like we need Tizen Studio and can't run as headless as we would like.

I really appreciate this tool.  One thing I've had to do is put the `silent: false` flags up on some of the `execSync` commands.  Even if that doesn't state the exact problem, it's still useful to have verbose output.

**Comment by prozanne** [comment]
Hi 👍 Thanks!
Happy New Year~

We are also considering and addressing to be independent from Tizen Studio.
Sorry for inconvenience until now, we will update it gradually.

And also, for debugging, we will consider supporting a verbose option not to make you change a source code directly!
Thanks.
Have a nice day.

**Comment by serkanbektas** [comment]
This issue seems to closable but I got same error message with different problem.

I got "**Failed to install Wits**" error after **Failed to uninstall Wits** warning.

There isnt any bug report else.
```
⇒ wits -s
 _      ____________
| | /| / /  _/_  __/__
| |/ |/ // /  / / (_-<
|__/|__/___/ /_/ /___/

Start running Wits............

[@tizentv/tools]tools.getToolPath: toolName = sdb

      > [ Stored Information ]

      > baseAppPath  : /Users/serkan/Works/smart/src
      > width        : 1920
      > deviceIp     : 192.168.1.38
      > isDebugMode  : true

      > profile path : /Users/serkan/.nvm/versions/node/v15.2.1/lib/node_modules/@tizentv/wits/resource/profiles.xml
      > hostIp       : 192.168.1.102

connect to....192.168.1.38
Success to connect 192.168.1.38
content src is : index.html

Start packaging Samsung Tizen TV Platform......

[webide-common-tizentv]projectHelper.buildWidget() profilePath = /Users/serkan/.nvm/versions/node/v15.2.1/lib/node_modules/@tizentv/wits/resource/profiles.xml, excludeFiles = undefined
After build package, signature tempory files were removed
[webide-common-tizentv]projectHelper.widget.on(): Build Package completed!
============================== Build Package completed!

============================== Start to install the package

[warning] Failed to uninstall Wits

Failed to install Wits
```

**Comment by prozanne** [comment]
Hi! 

First, happy new year!
And sorry for late reply.

Could you please let me know which tizen certification you created? (public/partner)

If you chose a tizen partner level, as I checked from Tizen Studio team, the security policy was changed not to support Tizen Partner anymore.
For this reason, unfortunately if you want to use "partner" level apis you should use only Samsung Partner certification which is not supported on WITs yet.

So, I think you have 2 options.
You can switch to public level of tizen certification, 
or please install Tizen Studio and use a partner level of Samsung certification.
Sorry for inconvenience.

Or perhaps you already use a public level of tizen certification, let me know again.
There might be another issue.

Best regards
Rosie

**Comment by serkanbektas** [comment]
Hello @prozanne,

I have installation problem with Tizen Studio on Big Sur and i thought I don't need to Tizen Studio if i use Wits but i understood that that way is wrong.

I've installed Tizen Studio and created required fields (certificate, profile). Now i can use Wits without an error.

Thank you.

**Comment by prozanne** [comment]
Sorry for inconvenience again.
We are also trying to be independent from Tizen Studio.
If WITs supports Samsung certification (TBD) , Tizen Studio will not be required anymore.

Thanks!
And this issue will be closed!

Best regards.
Rosie.

**Comment by chahatnagar-digivalet** [comment]
Hello @prozanne ,
I'm getting the following error while running the wits start command. I am using Partner level APIs, for that I have created Partner Level certificate from Tizen Studio.

```digi_user@E14-CD385:/var/www/html/tizen-tv-app/build$ wits -s deviceIp=172.24.0.238 --verbose
 _      ____________  
| | /| / /  _/_  __/__
| |/ |/ // /  / / (_-<
|__/|__/___/ /_/ /___/

Start running Wits............

[@tizentv/tools]tools.getToolPath: toolName = sdb

      > [ Stored Information ]

      > baseAppPath  : /var/www/html/tizen-tv-app/build
      > width        : 1920
      > deviceIp     : 172.24.0.238
      > isDebugMode  : true

      > profile path : /home/digi_user/tizen-studio-data.1/profile/profiles.xml
      > hostIp       : 172.24.0.125

WITs tries connecting with 172.24.0.238

connect to....172.24.0.238
172.24.0.238:26101 is already connected

Success to connect 172.24.0.238
List of devices attached 
172.24.0.238:26101      device          HG43AU800AKLXL

secure_protocol:enabled
intershell_support:disabled
filesync_support:pushpull
usbproto_support:disabled
sockproto_support:enabled
syncwinsz_support:enabled
sdbd_rootperm:disabled
rootonoff_support:disabled
encryption_support:disabled
zone_support:disabled
multiuser_support:enabled
cpu_arch:armv7
sdk_toolpath:/home/owner/share/tmp/sdk_tools
profile_name:tv
vendor_name:Samsung
can_launch:tv-samsung
device_name:Tizen
platform_version:6.0
product_version:4.0
sdbd_version:2.2.31
sdbd_plugin_version:3.8.4_TV_REL
sdbd_cap_version:1.0
log_enable:disabled
log_path:/tmp
appcmd_support:disabled
appid2pid_support:enabled
pkgcmd_debugmode:enabled
netcoredbg_support:enabled


content src is : index.html

Start packaging Samsung Tizen TV Platform......

[webide-common-tizentv]projectHelper.buildWidget() profilePath = /home/digi_user/tizen-studio-data.1/profile/profiles.xml, excludeFiles = undefined
[@tizentv/tools]tools.getToolPath: toolName = certificate-encryptor
cryptTool = /home/digi_user/tizentv-tools/certificate-encryptor/secret-tool
PKCS#12 MAC could not be verified. Invalid password?
PKCS#12 MAC could not be verified. Invalid password?```

**Comment by shologin** [comment]
Hi @chahatnagar-digivalet , have you been using Linux?

**Comment by chahatnagar-digivalet** [comment]
Yes

**Comment by shologin** [comment]
@chahatnagar-digivalet , I had the same problem. The thing is, WITs uses its own tool for managing certificates. 
When you create a new Samsung Certificate with Tizen Studio, the new profile into `/home/username/tizen-studio-data/profile/profiles.xml` is being added.
If you open `profiles.xml` you'll see the line like 
`<profileitem ca="" distributor="0" key="/path/to/author.p12" password="/path/to/author.pwd"`. This `/path/to/author.pwd` is like a kind of virtual path that is stored in your GNOME keyring. If you're running Ubuntu, you can find this password via tool called "seahorse" ("Passwords and Keys").

The problem is that WITs is using it's own tool for certificate encryption (`cryptTool = /home/digi_user/tizentv-tools/certificate-encryptor/secret-tool`), and when inside `.witsconfig.json` you point to `tizen-studio-data/profile/profiles.xml`, it tries to decrypt the password with this tool, and fails (due to difference between tools).

Solution.
You need to manually add your certificate into WITs' `cryptTool`. Here is the simple snippet which you can adjust and use to add profile:
```bash
export SECRET_TOOL="/home/username/tizentv-tools/certificate-encryptor/secret-tool"
export AUTHOR_PASSWORD="test1234" # password that you've entered when created your certificate
export AUTHOR_PWD_FILE="/home/username/path/to/author.pwd" # can be found at profiles.xml; often the same path as to author.p12 but extension is .pwd

$SECRET_TOOL store --label="tizen-studio" keyfile $AUTHOR_PWD_FILE tool certificate-manager --password $AUTHOR_PASSWORD
```

You can run `export SECRET_TOOL="/home/username/tizentv-tools/...` in your terminal and play around with this CLI. Command like `$SECRET_TOOL lookup` can be pretty helpful to check if your credentials are actually added.

**Comment by chahatnagar-digivalet** [comment]
@shologin I'll try the above solution and let you know. Thank for the help :)

**Comment by lucaskfp** [comment]
@chahatnagar-digivalet works?
