### ISSUE TITLE
Disconnected on WITs

### ISSUE THREAD

**Issue by serkanbektas** [Samsung/Wits#96]
I have a strange bug on WITs. Samsung TV model UE43TU7000XTK

```
============================== Start to install the package
listening on 2108
Chrome debugging port running on 56858
```

I have no error on console but when i started WITs I have this shot on TV
[https://i.hizliresim.com/didXzW.jpg](https://i.hizliresim.com/didXzW.jpg)

There isn't any action, nothing loading and i cant debug with TV.

**Comment by prozanne** [comment]
Hi

I guess the connection is unstable.
And, could you please update WITs to v2.5.0 (The latest version),
and start with verbose option.

ex) wits -s --verbose

Then you can get more details about the error!
If you still don't know what's the problem, please share the logs.
