### ISSUE TITLE
wits start giving error

### ISSUE THREAD

**Issue by shmdhussain** [Samsung/Wits#98]
I installed the wits globally and trying to setup the wits in emulator 

I setup the wits config using the `wits -i `command, see the screenshot below

<img width="1085" alt="Screenshot 2021-08-30 at 11 45 02" src="https://user-images.githubusercontent.com/4039657/131304981-1ec5afa2-88f4-4f16-b370-32c9c0bb1a87.png">

**then I started the wits in watch mode ,  `wits -w --verbose ` then I got the below error in the screenshot**

<img width="650" alt="Screenshot 2021-08-30 at 11 48 26" src="https://user-images.githubusercontent.com/4039657/131305085-1b9a865d-e74d-4963-be7e-bb4729e833d1.png">
<img width="1090" alt="Screenshot 2021-08-30 at 11 48 41" src="https://user-images.githubusercontent.com/4039657/131305138-9aa59ce7-2225-41d4-8709-9823c91e2983.png">

One Thing I noted is my app id in config.xml is `zPFhhtkB67.BasicProject` but in the command I am seeing in terminal I found it is trying to run app with this id `zPFhhtkB67.BasicProjectWITs`, seeing extra **WITS** in that

Please help me why I am getting this error, I am able to install and debug the app in the emulator through tizen studio.

thanks in advance for any help

**Comment by prozanne** [comment]
Hi :)

First, the reason why the package id has "WITS" at the end is WITs works on a container app.
BasicProjectWITs is only a container app, It's not a real your app. (watch your real source codes and push them on this app)
So It's normal.

And about the main issue, I need to check it more.
One thing I want to know is what kind of certification did you use? (Samsung - Public / Partner) or (Tizen - Public / Partner)

Thanks.
I will check it more.

**Comment by shmdhussain** [comment]
Thank you so much for your reply.

Understood the first point regarding the "WITS" add and the container app.

regarding the second point, I am using **samsung public certificate** .

If you need any more details I can help with you, facing lot of time in changing and seeing the update in the app, It will be much helpful If I am able to start running the WITS

**Comment by pwsses** [comment]
Hi.
It looks like failed debug launch, Is it success install on Emulator? 
I mean, Do you see WITs Icon in the emulator?
How about turn off debugMode? Set isDebugMode to false on .witsconfig.json.
Thank you.

**Comment by shmdhussain** [comment]
@pwsses as you said, I turned off the debug mode and I get the following error in the screenshot below
<img width="1114" alt="Screenshot 2021-09-01 at 11 23 57" src="https://user-images.githubusercontent.com/4039657/131629936-0678e176-10cb-4484-9094-a1c7ffb6d466.png">

I am running on Mac OS Big sur 11.4.

I am able to run the app through command line(I gave those commands below) and tizen studio (_run as_ and _debug as_ options)

```
tizen build-web -- ./
tizen package -t wgt -s testsamcert -- ./.buildResult/
tizen install -s emulator-26101 --name "BasicProject.wgt" -- ./.buildResult
tizen run -s emulator-26101 -p zPFhhtkB67.BasicProject 
```

I am able to attach the debugger to the application through 

`sdb -s emulator-26101 shell 0 debug zPFhhtkB67.BasicProject `

**Comment by pwsses** [comment]
hi. thank you for detail report.
Most of the error occur in the installation with certificate issue, and there should be no problems in launch.

`I am able to install the app in emulator through tizen studio(from run as "web applications")
I don't see any WITS icon(I don't know how the WITS icon looks like), I see only the app icon which i used to install through tizen studio,`
=> WITs container app use your app package value. so you have to remove your application.
and WITs container App icon is below. 
![image](https://user-images.githubusercontent.com/11974693/131634750-d5e4e046-9a6a-45df-8296-02e165601630.png)

 when you start wits, wits make container app package(wgt) based on your app config.xml. and install container app to target.
so you don't need install your app.

`And also I am getting the error in the emulator(on top of any opened application) like the below screenshot, after running the wits -w --verbose command`
I think, WITs does not any affect other App execution but if it repeats, you will have to create a new emulator.
I'm sorry it's not a clear answer.

**Comment by shmdhussain** [comment]
@pwsses thanks again, 

**=> WITs container app use your app package value. so you have to remove your application.** ==> this made my app working, I uninstalled the app, run the `wits -s` then app starts working with WITS 🎉🎉

then I changed the code , it is reflecting in the emulator. 

Now my doubt is what is the difference between `wits -s` and `wits -w`, I understand that **w** means watch files and  update in the device, but `wits -`s itself is doing that job(changing code , reflecting in `wits -s `too).

**Comment by pwsses** [comment]
@shmdhussain Good.
As you said, there are supported live reload but,
wits -s is container app package and install and launch. 
wits -w is just launch container app without package and install.
so If your container app had installed, Use wits -w it will be faster.

**Comment by shmdhussain** [comment]
Then I found , either the WITS version or the original app can be present in the device/emulator. we need to uninstall one of it to make the other work.

I am closing the issue as WITS working for me now.

thank u so much for the help @prozanne  @pwsses
